name: 'Firewatch'
description: 'Creates slack alerts when an issue in the repository receives reactions faster than a specified threshold.'
inputs:
  github_token:
    description: 'A valid github token.'
    required: true
  alert_threshold:
    description: 'Threshold to use when determining alert status of an issue.'
    required: true
  issue_age_months:
    description: 'Age of issues to include.'
    required: true
  slack_token:
    description: 'A bot token with the correct scope.'
    required: true
  slack_channel:
    description: 'Channel identifier'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
